# Generated by Django 3.2.12 on 2022-04-07 04:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projectsmodel',
            name='author',
        ),
        migrations.RemoveField(
            model_name='projectsmodel',
            name='body',
        ),
        migrations.RemoveField(
            model_name='projectsmodel',
            name='time',
        ),
    ]
